#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely. Sleep 2 is added between each iteration of the loop.

i=1
while [ $i -gt 0 ]; do

    echo "To infinity and beyond"

    sleep 2

done
