#!/usr/bin/env bash
# This script displays Best School 10 times using the while loop and the if statement. It displays Hi after the 9th iteration on a new line.

i=1

while [ $i -le 10 ]; do
    
    echo "Best School"
    
    if [ $i -eq 9 ]; then
	echo "Hi"
    fi
    ((i++))
    
done
