#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and "bad luck from China" for the 4th loop, "bad luck from Japan" for the 9th loop, and "bad luck from Italy" for the 17th loop. It uses the while loop and the case statement.

i=1

while [ $i -lt 21 ]; do

    echo $i

        case $i in
	    4)
	        echo "bad luck from China"
	        ;;
	    9)
	        echo "bad luck from Japan"
	        ;;
	    17)
	        echo "bad luck from Italy"
	        ;;
        esac
        ((i++))

done
     
     
		 
