#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes using the while loop

H=0
while [ $H -lt 13 ]; do

    echo "Hour: $H"
    
    M=1
    while [ $M -lt 60 ]; do

	echo $M
	M=$((M + 1))

    done
    H=$((H + 1))

done

